global:
  scrape_interval:     15s

  external_labels:
    monitor: 'problematic-monitor'

scrape_configs:
  - job_name: 'problematic-exporter'
    scrape_interval: 5s
    metrics_path: '/firehose/resources/metrics'
    static_configs:
      - targets: ['problematic:8090']